### PR TITLE
Update runtime to GNOME 42

### PR DESCRIPTION
**Pull request by Eonfge**
Also fix the build script and add some much needed x-data-checkers

---

Not everything is fixed though. Some follow-up issues:
- Latest Gstreamer versions compatible with the runtime (1.18.x)
- Updated Python dependencies

If you need some help with those things, let me know @lazka

### CODE REVIEW

**Comment by lazka** [comment]
Lots of things broken, libsoupd 2/3 conflicts, the unbundling of ffmpeg didn't really work (wma and mpc fail to decode)

**Comment by Eonfge** [comment]
Tested some .wma files and they seem to work now. I also supervise the Lollypop package (https://github.com/flathub/org.gnome.Lollypop) so that one has a lot in common with this package. Using the FFmpeg module so you can have proprietary audio support is the easiest.

**Comment by lazka** [comment]
thanks. It still doesn't contain all the codecs to get the test suite to pass, so I'll switch back to building ffmpeg.

I'll try some things in #21 minus the runtime update in the meantime.

**Comment by lazka** [comment]
Partly included in #21, so closing

**Pull request closed without merging**
