### PR TITLE
Some Updates & Cleanup

### PR DESCRIPTION
**Pull request by lazka**

### CODE REVIEW

**Comment by Eonfge** [comment]
It's a shame that GNOME 42 throws such a conflict, but cool to see that there are still some improvements to be made. 

One additional improvement, x-checker-data config for gme:
```
        x-checker-data:
          type: anitya
          project-id: 866
          url-template: https://bitbucket.org/mpyne/game-music-emu/downloads/game-music-emu-$version.tar.xz
```

Finally, two questions;
- Should we try GNOME 41?
- Should we try FFmpeg 5.0?

**Comment by lazka** [comment]
> * Should we try GNOME 41?

Yes, I'll create a new PR for that

> * Should we try FFmpeg 5.0?

Not sure if the included gstreamer releases work with that. 4.4 is still supported, so no need to force this imo.

**Comment by Eonfge** [comment]
Sounds good. We don't have to update everything in one go. Small steps win the race and I gladly help with some future pull requests.

**Comment by lazka** [comment]
41 update in #22

**Pull request merged**
